<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta name="title" content="Sign Succeed">
    <meta name="apple-touch-fullscreen" content="YES">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <title>掌上党校</title>
    <link href="/css/home.css" rel="stylesheet" type="text/css" />
</head>

<body>
    <div class = "main">
        <img src="/images/home_bg.jpg" height="100%" width="100%"/>
        <div id = "home">
            <a href="###" ><img src="/images/home.jpg" height="100%" width="100%"/></a>
        </div>
        <div id = "module1">
            <a href="/index/registration" ><img src="/images/module1.png" height="100%" width="100%"/></a>
        </div>
        <div id = "module2">
            <a href="/index/lists" ><img src="/images/module2.png" height="100%" width="100%"/></a>
        </div>
        <div id = "module3">
            <a href="/index/test" ><img src="/images/module3.png" height="100%" width="100%"/></a>
        </div>
        <div id = "module4">
            <a href="/index/warning" ><img src="/images/module4.png" height="100%" width="100%"/></a>
        </div>

        <div id = "notice">
            <p>如果是第一次登陆，请先<a href="http://weixin.hfutonline.net/verifi.php?k=oTIKct0oS3Dg9p7T1YmGOQKSFh_o">实名认证</a>哦！</p>
        </div>
    </div>

</body>
</html>