<!DOCTYPE html>
<html>
 	<head>
	  <meta charset="UTF-8">
  	  <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
	  <title>报名注册</title>
	  <link rel="stylesheet" href="/css/bootstrap.css">
	  <style>
	  	.container{width: 90%;margin: 10px auto;}
	  	.container .con-title{
	  		width: 100%;
	  		text-align: center;
	  	}
	  	.container form .height-input{
	  		height: 3em;
	  		margin-bottom: 1.5em;
	  	}
	  </style>
	</head>
	<body>
		<div class="container">
			<div class="con-title">
				<h2>党校报名注册</h2>
			</div>
			<form action="">
			<input class="form-control height-input" type="text" placeholder="学号" required>
			<input class="form-control height-input" type="text" placeholder="姓名" required>
			<input class="form-control height-input" type="text" placeholder="性别" required>
			<input class="form-control height-input" type="text" placeholder="学院名称" required>
			<input class="form-control height-input" type="text" placeholder="党校班级名称" required>
			<input class="form-control height-input" type="number" placeholder="手机号码" required>
			<button class="btn btn-primary btn-lg btn-block btn-login" type="submit">党校报名</button>
		</form>
		</div>
	</body>
</html>