<!DOCTYPE html>
<html>
 	<head>
	  <meta charset="UTF-8">
  	  <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
	  <title>报名注册</title>
	  <link rel="stylesheet" href="/css/bootstrap.css">
	  <style>
	  	.container{width: 90%;margin: 10px auto;}
	  	.container .con-title{
	  		width: 100%;
	  		text-align: center;
	  	}
	  	.container form .height-input{
	  		height: 3em;
	  		margin-bottom: 1.5em;
	  	}
	  </style>
	</head>
	<body>
		<div class="container">
			<div class="con-title">
				<h2>党校报名注册</h2>
			</div>
			<form action="" method="post">
			<input class="form-control height-input" type="text" name="stuid" placeholder="学号" required>
			<input class="form-control height-input" type="text" name="stuname" placeholder="姓名" required>
			<!-- <input  type="text" placeholder="性别" required> -->
			<select class="form-control height-input" name="sex">
			    <option value="" disabled selected style="display:none;"> -- 性别 -- </option>
				<option value="男">男</option>
				<option value="女">女</option>
			</select>
			<select class="form-control height-input" name="periodsnum">
			    <option value="" disabled selected style="display:none;"> -- 期数 -- </option>
			    <?php
			      	echo '<option value="'.$this->periodnum.'">'.$this->periodnum.'</option>';
			    ?>
			</select>
			<select class="form-control height-input" name="campus">
			    <option value="" disabled selected style="display:none;"> -- 校区 --</option>
			    <option>翡翠湖校区</option>
			    <option>屯溪路校区</option>
			</select>
			<select class="form-control height-input" name="depid">
			    <option disabled selected style="display:none;"> -- 学院 -- </option>
			    <?php
			       for ($i=1; $i < 20; $i++)
			       {
			       	 echo "<option value='".$this->depart[$i]['depid']."'>".$this->depart[$i]['depname']."</option>";
			       }
			    ?>
			</select>
			<select class="form-control height-input" name="classtype">
			    <option value="" selected disabled  style="display:none;"> -- 班级类别 -- </option>
			    <option >积极分子班</option>
			    <option >党员班</option>
			</select>
			<input class="form-control height-input" type="number" placeholder="手机号码" name="phone" required>
			<button class="btn btn-primary btn-lg btn-block btn-login" type="submit">党校报名</button>
		</form>
		<a href="/index">返回首页</a>
		</div>
	</body>
</html>