<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
	<meta name="title" content="Sign Succeed">
	<meta name="apple-touch-fullscreen" content="YES">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="format-detection" content="telephone=no">
	<title>掌上党校</title>
	<link href="/css/base.css" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" type="text/css" href="/css/grade_registration.css">
	<style>
		#content p{
			top:10%;
			text-indent:2em;
		}
		
	</style>
</head>

<body>
	<div class = "main">
		<img src="/images/base_bg.jpg" height="100%" width="100%"/>
		<div id = "home">
			<a href="../" ><img src="/images/home.jpg" height="100%" width="100%"/></a>
		</div>
		<div id="content">
			<img src="/images/border.png">
			<img src="/images/making.gif" alt="">
			<p>亲，你少了哪一步了？实名认证必须要滴，报名之后才能测试哦，测试才有成绩</p>
		</div>
	</div>

</body>
</html>