<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN"
"http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
	<meta name="title" content="Sign Succeed">
	<meta name="apple-touch-fullscreen" content="YES">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="format-detection" content="telephone=no">
	<title>Test</title>
	<script type="text/javascript" src="/js/choose.js"></script>
	<script type="text/javascript" src="/js/base.js"></script>
	<link href="/css/base.css" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" type="text/css" href="/css/test.css">
	<style type="text/css">
		
	</style>
</head>

<body>
	<div class = "main">
		<img src="/images/base_bg.jpg" height="100%" width="100%"/>
		<div id = "home">
			<a href="../" ><img src="/images/home.jpg" height="100%" width="100%"/></a>
		</div>
		<div id="content">
			<ul class="time">
				<li>本次测试共<span>10题</span></li>
				<li>测试间<span>20</span>分钟</li>
				<li>剩余时间：<span>01:20</span></li>
			</ul>
			<div class="question" id="que">
				<p>1、中国房产当是中国工人阶级的先锋队，表明了党的（）</p>
				<ul>
					<li>A、阶级性</li>
					<li>B、民主性</li>
					<li>C、群众性</li>
					<li>D、先进性</li>
				</ul>
				
			</div>
			<ul class="button">
				<li><input type="button" value="上一题"></li>
				<li><input type="button" value="下一题"></li>
			</ul>
		</div>
	</div>

</body>