<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>超级管理员-基本设置</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/baseSeting.css">
    <link id="artDialogSkin" href="/skin/aero/aero.css" rel="stylesheet" type="text/css" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!-- [if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif] -->
  </head>
  <body>
  <!-- 头部导航 -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand" style="color:#FFF;font-size: 20px;">掌上党校管理系统</span>
        </div>
        <div class="navbar-collapse collapse" role="navigation">
            <ul class="nav navbar-nav">
              <li><a href="/admin/baseset" style="color: #FFF;">基本设置</a></li>
              <li><a href="/admin/xyinfo">学员信息</a></li>
              <li><a href="/admin/questionset">题目设置</a></li>
              <li><a href="/admin/queupdate">修改题库</a></li>
              <li><a href="/admin/learninfo">学习资讯</a></li>
             <!--  <li><a href="psmangement.html">班主任密码</a></li> -->
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <li><a href="/login/logout"><span style="color: #FFF">欢迎您，<?php $session = new Zend_Session_Namespace('user'); echo $session->realname;?></span>  退出</a></li>
            </ul>
        </div>
      </div>
  </div>
  <!-- 页面内容 -->
  <div id="main">
    <div class="main-content">

      <div class="content-form">


        <?php 


        echo
        "<form class=\"form-horizontal\" role=\"form\" action =\"/admin/baseset\" method =\"post\">
          <div class=\"content-title\">
              <h3>第<input name=\"periodnum\" type=\"text\" class=\"form-control\" value=\"".$this->periodnum."\">期党校党员班</h3>
          </div>
          <div class=\"group-form\">  
              <label for=\"baoming\">报名时间：</label>
              <input name=\"enrollstart\" type=\"date\" class=\"form-control form-date\" id=\"baoming\" value=\"".$this->enrollstart."\">
              <span class=\"time-len\">——</span>
              <input name=\"enrollend\" type=\"date\" class=\"form-control form-date\" id=\"bg-end\" value=\"".$this->enrollend."\">
          </div>
          <div class=\"group-form\">
              <label for=\"test\">测试时间：</label>
              <input name=\"able_test_start\" type=\"date\" class=\"form-control form-date\" id=\"test\" value=\"".$this->sum_start."\">
              <span class=\"time-len\">——</span>
              <input name=\"able_test_end\" type=\"date\" class=\"form-control form-date\" id=\"test-end\" value=\"".$this->sum_end."\">
          </div>
          <div class=\"group-form\">
            <label for=\"dangxiao\">党校总结：</label>
              <input name=\"sum_start\" type=\"date\" class=\"form-control form-date\" id=\"dangxiao\" value=\"".$this->able_test_start."\">
              <span class=\"time-len\">——</span>
              <input name=\"sum_end\" type=\"date\" class=\"form-control form-date\" id=\"dg-end\" value=\"".$this->able_test_end."\">
          </div>   
          <div class=\"form-group form-pos\">
          </div>
          <div class=\"form-group from-pos formbtn-right\">
            <div class=\"col-sm-3 submit-change\">
              <button type=\"submit\" id=\"set-submit\" class=\"btn btn-primary\">提交设置</button>
            </div>
          </div>
        </form>" ?>
      </div>
    </div>
  </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/artDialog.js"></script>
    <script type="text/javascript" src="/js/base.js"></script>
  </body>
</html>