<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta charset="UTF-8">
	<title>党校总结</title>
	<link rel="stylesheet" href="/css/bootstrap.css">
  <link rel="stylesheet" href="/css/xyinfo.css">
  <link rel="stylesheet" href="/css/dxzj.css">
  <!-- 弹窗样式 -->
  <link id="artDialogSkin" href="/skin/aero/aero.css" rel="stylesheet" type="text/css" />
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="/assets/js/html5shiv.min.js?v=f7c242d291"></script>
  <script src="/assets/js/respond.min.js?v=f7c242d291"></script>
<![endif]-->
<!-- Favicons -->
</head>
<body class="home-template">
	<div class="navbar navbar-inverse navbar-fixed-top">
  		<div class="container">
    		<div class="navbar-header">
      			<button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        			<span class="sr-only">Toggle navigation</span>
        			<span class="icon-bar"></span>
        			<span class="icon-bar"></span>
        			<span class="icon-bar"></span>
      			</button>
      			<span class="navbar-brand" style="color:#FFF;font-size: 20px;">党校党班管理系统</span>
    		</div>
    		<div class="navbar-collapse collapse" role="navigation">
      			<ul class="nav navbar-nav">
        			<li><a href="/admin/dxzj" style="color: #FFF;">党校总结</a></li>
        			<li><a href="/admin/percenter">个人中心</a></li>
      			</ul>
      			<ul class="nav navbar-nav navbar-right">
        		<li><a href="/login/logout"><span style="color: #FFF">欢迎您， <?php echo $this->realname;?></span>  退出</a></li>
      			</ul>
    		</div>
  		</div>
	</div>
  <!-- 页面内容 -->
  <div class="main-container">
    <div class="main-title">
      <h2>第<?php echo $this->classid;?>期党校党员班学员信息表</h2>
        <label>校区:</label>
        <span><?php echo $this->campus;?></span>
        
        <label>学院：</label>
        <span><?php echo $this->depname;?></span>

        <label>班级：</label>
        <span><?php echo $this->classtype;?></span>

        <a href="/admin/xls" class="btn btn-info">生成excel</a>
    </div>
    <div class="main-content">
      <!-- <form> -->
        <table class="table table-hover">
          <thead>
            <tr>
              <th><img src="/images/add.png" alt="添加新学员" id="addXueyuan"></th>
              <th>学号</th>
              <th>姓名</th>
              <th>手机号码</th>
              <th>性别</th>
              <th>优秀状态</th>
              <th>毕业状态</th>
              <th>成绩</th>
            </tr>
          </thead>
          <tbody>
            <?php
              if ($this->paginator_studentinfo)
              {
                foreach ($this->paginator_studentinfo as $stuList)
                {
                  $stno = $stuList['stno'];
                  $stuname = $stuList['name'];
                  $stuphone = $stuList['phonenum'];
                  $sex = $stuList['sex'];
                  $score = $stuList['grade'];
                  if ($score == '')
                  {
                    $score = "暂无成绩";
                  }
                  $isgood = "非优秀";
                  $isgraduate = "非毕业";
                  if ($stuList['isgood'] == 1)
                  {
                    $isgood = "优&nbsp;&nbsp;&nbsp;秀";
                  }
                  if ($stuList['isgraduate'] == 1) {
                    $isgraduate = "已毕业";
                  }

                  echo "<tr>";
                  echo '<td><input type="checkbox" name="xueyuan" class="form-control check-change"></td>';
                  echo "<td>{$stno}</td>";
                  echo "<td>{$stuname}</td>";
                  echo "<td>{$stuphone}</td>";
                  echo "<td>{$sex}</td>";
                  echo '<td><button class="btn btn-default youxiu" id="'.$stno.'">'.$isgood.'</button></td>';
                  echo '<td><button class="btn btn-default biye" id="'.$stno.'">'.$isgraduate.'</button></td>';
                  echo "<td>{$score}</td>";
                  echo "</tr>";
                }
              }
              else
              {
                echo "no";
              }

              global $arrList;
              $paginator_all=$this->paginator_all;
            ?>
          </tbody>
        </table>
        <div class="footer-fenye">
          <ul class="pager">
             <?php echo $this->paginationControl($this->paginator_studentinfo,
                'Elastic',//页码样式 
                'admin/pagination_control.phtml'//页码模板
                );
            ?>
          </ul>
        </div>
        <button type="button" class="btn btn-danger" id="all-del">一键删除</button>
      <!-- </form> -->
       <!-- 优秀学员 -->
        <div class="students-yx info">
          <label for="st-yx">优秀学员姓名（人数占所带学生总人数10%）</label>
          <textarea name="st-yx" id="st-yx" class="form-control" disabled>自动显示优秀学员姓名</textarea>
        </div>

      <!-- 党校总结表单 -->
      <form class="form-horizontal" role="form" method="post" action="/admin/dxzj">
        <!-- 学员素质 -->
        <div class="info">
          <label for="xy-sz">如何严格招生，保证学员素质（措施、效果）</label>
          <textarea name="xy-sz" id="xy-sz" class="form-control"><?php echo $this->xysz;?></textarea>
        </div>
        <!-- 学习情况 -->
        <div class="info">
          <label for="study-content">组织集中学习情况（主题、次数、效果）</label>
          <textarea name="study-content" id="study-content" class="form-control"><?php echo $this->study;?></textarea>
        </div>
        <!-- 讨论情况 -->
        <div class="info">
          <label for="taolun-content">组织讨论情况（主题、次数、效果）</label>
          <textarea name="taolun-content" id="taolun-content" class="form-control"><?php echo $this->taolun;?></textarea>
        </div>
        <!-- 实践活动情况 -->
        <div class="info">
          <label for="">开展实践活动情况（主题、形式、意义、效果）</label>
          <textarea name="shijian-content" id="shijian-content" class="form-control"><?php echo $this->shijian;?></textarea>
        </div>
        <div class="info">
          <button id="button" class="btn btn-info submit">提交</button>
        </div>
      </form>
    </div>
  </div>
	<script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
	<script type="text/javascript" src="/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="/js/artDialog.js"></script>
  <script type="text/javascript" src="/js/dangxiaozongjie.js"></script>
  <script type="text/javascript" src="/js/xueyuanChange.js"></script>
</body>
</html>