<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>超级管理员-学习资讯</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/lninfo.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- 头部导航 -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand" style="color:#FFF;font-size: 20px;">掌上党校管理系统</span>
        </div>
        <div class="navbar-collapse collapse" role="navigation">
            <ul class="nav navbar-nav">
              <li><a href="/admin/baseset">基本设置</a></li>
              <li><a href="/admin/xyinfo">学员信息</a></li>
              <li><a href="/admin/questionset">题目设置</a></li>
              <li><a href="/admin/queupdate">修改题库</a></li>
              <li><a href="/admin/learninfo" style="color: #FFF;">学习资讯</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <li><a href="/login/logout"><span style="color: #FFF">欢迎您，  超级管理员</span>  退出</a></li>
            </ul>
        </div>
      </div>
    </div>
    <!-- 页面内容 -->
    <div class="main-container">
      <div class="main-title">
        <a href="/admin/addzx">
          <button type="button" class="btn btn-info">添加新文章</button>
        </a>
      </div>
      <div class="main-content">
        <form>
          <!-- 文章列表 -->
          <div class="title-container">
               
            
                
                    <?php
                      if ($this->paginator_learninfo) {
                        foreach ($this->paginator_learninfo as $artcileList) {
                          $id = $artcileList['id'];
                          $publisedtime = date('Y-m-d',$artcileList['publisedtime']);
                          $title = $artcileList['title'];
/*                          $len = strlen($title);
                          if ($len > 51) {
                            $title = substr($title, 0,39)."...";
                          }*/
                          // echo "zishu:".strlen($title);
                          ?>
                          <div class="checkbox">
                            <label>
                              <input type="checkbox">
                                <?php
                                echo "<a href='/index/article/id/".$id."'>".$title."</a>";
                                ?>
                            </label>
                            <button type="button" class="btn btn-default">修改</button>
                          </div>
                          <?php
                        }
                      }else{
                        echo "shit";
                      }
                    ?>
              
              
            
          </div>
          <tbody>

            <?php
              global $arrList;
              $paginator_all=$this->paginator_all;

            ?>
          
          </tbody>
        <div class="footer-fenye">
          <ul class="pager">
            <?php echo $this->paginationControl($this->paginator_learninfo,
                'Elastic',//页码样式 
                'admin/pagination_control.phtml'//页码模板
                );
            ?>
          </ul>
        </div>
      </div>
         
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
  </body>
</html>