<ul>

<?php
	if(!empty($_GET["periodnum"])&!empty($_GET["testtime"])&!empty($_GET["timunum"])){
	    $periodnum = $_GET["periodnum"];
	    $testtime = $_GET["testtime"];
	    $timunum = $_GET["timunum"];
	    $page_url = "?&periodnum=".$periodnum."&testtime=".$testtime."&timunum=".$timunum;
	}else{
		$page_url = "";
    }
    
		if ($this->previous==1)
			$tmp = $this->url(array('page'=>null));
		else
			$tmp = $this->url(array('page'=>$this->previous));
		if($this->previous!=null)

			echo "<li><a href=\"$tmp".$page_url."\">&laquo; 上一页</a></li>";
		else
			echo "&laquo; 上一页";

		$tmp = $this->url(array('page'=>$this->next));
		if($this->next!=null)
			echo "<li><a href=\"$tmp".$page_url."\">下一页 &raquo;</a></li>";
		else
			echo "下一页 &raquo;";
	
?>

</ul>

