<ul>

<?php
	if ($this->previous==1)
		$tmp = $this->url(array('page'=>null));
	else
		$tmp = $this->url(array('page'=>$this->previous));
	if($this->previous!=null)
		echo "<li><a href=\"$tmp\">&laquo; 上一页</a></li>";
	else
		echo "&laquo; 上一页";

/*	foreach ($this->pagesInRange as $page){
		if ($page != $this->current) {
			if ($page==1)
				$url = $this->url(array('page'=>null));
			else
				$url = $this->url(array('page'=>$page));
			echo "<li><a href=\"$url\">$page</a></li>";
		} else
			echo "<li class=\"active\">$page</li>";
	}*/

	$tmp = $this->url(array('page'=>$this->next));
	if($this->next!=null)
		echo "<li><a href=\"$tmp\">下一页 &raquo;</a></li>";
	else
		echo "下一页 &raquo;";
?>

</ul>