<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>超级管理员-题目设置</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/tkchange.css">
    <link rel="stylesheet" href="/css/qessetting.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- 头部导航 -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand" style="color:#FFF;font-size: 20px;">掌上党校管理系统</span>
        </div>
        <div class="navbar-collapse collapse" role="navigation">
            <ul class="nav navbar-nav">
              <li><a href="/admin/baseset">基本设置</a></li>
              <li><a href="/admin/xyinfo">学员信息</a></li>
              <li><a href="/admin/questionset"  style="color: #FFF;">题目设置</a></li>
              <li><a href="/admin/queupdate">修改题库</a></li>
              <li><a href="/admin/learninfo">学习资讯</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <li><a href="/login/logout"><span style="color: #FFF">欢迎您， <?php $session = new Zend_Session_Namespace('user'); echo $session->realname;?></span>  退出</a></li>
            </ul>
        </div>
      </div>
    </div>
    <!-- 页面内容 -->
    <div class="main-container">
      <div class="main-title">
        <?php 
        $periodnum=$this->periodnum;
        $testtime=$this->testtime;
        $timunum=$this->timunum;


        echo
          "<form action =\"/admin/questionset\" method =\"post\">
          <span>第</span>
          <input name=\"periodnum\" type=\"text\" class=\"form-control classdate\" value=\"".$periodnum."\">
          <span>期</span>
          
          <label for=\"test-time\">测试时间:</label>
          <input name=\"testtime\" type=\"time\" class=\"form-control\" id=\"test-time\" value=\"".$testtime."\">
          
          <label for=\"timu-num\">题目数量:</label>
          <input name=\"timunum\" type=\"text\" class=\"form-control\" id=\"timu-num\" placeholder=\"输入题目数量\" value=\"".$timunum."\">

          <button type=\"submit\" class=\"btn btn-info\">抽取</button>
        </form>" ?>
      </div>
      <!-- 例题 -->
      <div class="ques-exp">
        <div class="exp-container">
         <h3>例题：</h3>
          <div class="question">
            <p>1.中国共产党的最高理想和最终目标是（  ）</p>
            <p>(A)实现共产主义；</p>
            <p>(B)实现共产主义社会制度；</p>
            <p>(C)实现中国特色社会主义宏伟目标</p>
            <p>(D)实现中国特色社会主义宏伟目标</p>
            <span>正确答案：（A）</span>
          </div>
        </div>
      </div>
      <h3>抽取题目如下：</h3>
        <?php
          if ($this->paginator_choose) {
            foreach ($this->paginator_choose as $questionsetList) {
              $qeid = $questionsetList['qeid'];          
              $qetitle = $questionsetList['qetitle'];
              $ansA = $questionsetList['ansA'];
              $ansB = $questionsetList['ansB'];
              $ansC = $questionsetList['ansC'];
              $ansD = $questionsetList['ansD'];
              $ansY = $questionsetList['ansY'];
              echo "<div class=\"question-container\"><div class=\"question\">"."<p>".$qetitle."</p><p>".$ansA."</p><p>".$ansB."</p><p>".$ansC."</p><p>".$ansD."</p><span>"."正确答案：".$ansY."</span></div></div>";
            }
          }else{
            echo "shit";
          }
        ?>

      <tbody>

        <?php
          global $arrList;
          $paginator_choose=$this->paginator_choose;

        ?>
      
      </tbody>

      <div class="footer-fenye">
          <ul class="pager">
            <?php echo $this->paginationControl($this->paginator_choose,
                'Elastic',//页码样式 
                'admin/pagination_control.phtml'//页码模板
                );
              ?>

          </ul>
        </div>
      </div>
          
            
        <!-- 题目容器 -->
<!--         <div class="question-container">
          <div class="question">
            <p>2.中国共产党的最高理想和最终目标是（  ）</p>
            <p>(A)实现共产主义；</p>
            <p>(B)实现共产主义社会制度；</p>
            <p>(C)实现中国特色社会主义宏伟目标</p>
            <p>(D)实现中国特色社会主义宏伟目标</p>
            <span>正确答案：（A）</span>
          </div>
        </div> -->



    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
  </body>
</html>
