<!DOCTYPE html>

<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>超级管理员-修改题库</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/tkchange.css">
    <!-- 弹窗样式 -->
    <link id="artDialogSkin" href="/skin/aero/aero.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- 头部导航 -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand" style="color:#FFF;font-size: 20px;">掌上党校管理系统</span>
        </div>
        <div class="navbar-collapse collapse" role="navigation">
            <ul class="nav navbar-nav">
              <li><a href="/admin/baseset">基本设置</a></li>
              <li><a href="/admin/xyinfo">学员信息</a></li>
              <li><a href="/admin/questionset">题目设置</a></li>
              <li><a href="/admin/queupdate" style="color: #FFF;">修改题库</a></li>
              <li><a href="/admin/learninfo">学习资讯</a></li>
             <!--  <li><a href="psmangement.html">班主任密码</a></li> -->
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <li><a href="/login/logout"><span style="color: #FFF">欢迎您，  超级管理员</span>  退出</a></li>
            </ul>
        </div>
      </div>
    </div>
    <!-- 页面内容 -->
    <div class="main-container">
      <div class="main-title">
        <button type="button" class="btn btn-info" id="addTimu">添加题目</button>
        <button type="button" class="btn btn-info">全部题库</button>
      </div>

        <?php
          if ($this->paginator_all) {
            foreach ($this->paginator_all as $questionsetList) {
              $qeid = $questionsetList['qeid'];          
              $qetitle = $questionsetList['qetitle'];
              $ansA = $questionsetList['ansA'];
              $ansB = $questionsetList['ansB'];
              $ansC = $questionsetList['ansC'];
              $ansD = $questionsetList['ansD'];
              $ansY = $questionsetList['ansY'];
              echo "<div class=\"question-container\"><div class=\"question\">"."<p>".$qetitle."</p><p>".$ansA."</p><p>".$ansB."</p><p>".$ansC."</p><p>".$ansD."</p><span>"."正确答案：".$ansY."</span></div>
                      <div class=\"question-control\">
                          <button type=\"button\" class=\"btn btn-info update-btn\" id=\"editTimu\" qeid=\"".$qeid."\" timu=\"".$qetitle."\" ansA=\"".$ansA."\" ansB=\"".$ansB."\" ansC=\"".$ansC."\" ansD=\"".$ansD."\" rightAns=\"".$ansY."\">更新</button>
                          <a href=\"/admin/deletequestion/qeid/".$qeid."><button type=\"button\" class=\"btn btn-danger del-btn\">删除</button></a>
                      </div>
                    </div>";
            }
          }else{
            echo "shit";
          }
        ?>
      <tbody>
      <tbody>

        <?php
          global $arrList;
          $paginator_all=$this->paginator_all;

        ?>
      
      </tbody>

  
      
      <div class="footer-fenye">
          <ul class="pager">
            <?php echo $this->paginationControl($this->paginator_all,
                'Elastic',//页码样式 
                'admin/pagination_control.phtml'//页码模板
                );
              ?>

          </ul>
        </div>
      </div>

    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/artDialog.js"></script>
    <script type="text/javascript" src="/js/tikuChange.js"></script>
    <script type="text/javascript" src="/js/tikuEdit.js"></script>
  </body>
</html>