<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>超级管理员-学员信息</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/xyinfo.css">
    <link id="artDialogSkin" href="/skin/aero/aero.css" rel="stylesheet" type="text/css" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- 头部导航 -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand" style="color:#FFF;font-size: 20px;">掌上党校管理系统</span>
        </div>
        <div class="navbar-collapse collapse" role="navigation">
            <ul class="nav navbar-nav">
              <li><a href="/admin/baseset">基本设置</a></li>
              <li><a href="/admin/xyinfo" style="color: #FFF;">学员信息</a></li>
              <li><a href="/admin/questionset">题目设置</a></li>
              <li><a href="/admin/queupdate">修改题库</a></li>
              <li><a href="/admin/learninfo">学习资讯</a></li>
             <!--  <li><a href="psmangement.html">班主任密码</a></li> -->
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <li><a href="/login/logout"><span style="color: #FFF">欢迎您，<?php $session = new Zend_Session_Namespace('user'); echo $session->realname;?></span>  退出</a></li>
            </ul>
        </div>
      </div>
    </div>
    <!-- 页面内容 -->
    <div class="main-container">
      <div class="main-title">
        <form method="get" action="">
          <span>第</span>
          <input type="text" class="form-control classdate" name="periodnum">
          <span>期</span>
          <!-- 校区 -->
          <label for="xiaoqu">校区</label>
          <select name="xiaoqu" id="xiaoqu" class="form-control">
            <option>屯溪路</option>
            <option>翡翠湖</option>
          </select>
          <!-- 学院 -->
          <label for="xueyuan">学院</label>
          <select name="xueyuan" id="xueyuan" class="form-control">
            <?php
             for ($i=1; $i < 20; $i++)
             {
               echo "<option value='".$this->depart[$i]['depid']."'>".$this->depart[$i]['depname']."</option>";
             }
          ?>
          </select>
          <!-- 班级 -->
          <label for="banji">班级</label>
          <select name="banji" id="banji" class="form-control">
            <option>党员班</option>
            <option>积极分子班</option>
          </select>
          <button type="submit" class="btn btn-info" id="search">查询</button>
        </form>
      </div>
      <?php
      //判断是否有查询行为
        if ($this->paginator_studentinfo)
        {
      ?>
      <div class="main-content">
        <div class="contentdiv">
          <table class="table table-hover">
            <tr>
              <th>#</th>
              <th>学号</th>
              <th>姓名</th>
              <th>手机号</th>
              <th>年级</th>
              <th>优秀状态</th>
              <th>毕业状态</th>
              <th>成绩</th>
              <th>删除</th>
            </tr>
            <?php
                foreach ($this->paginator_studentinfo as $stuList)
                {
                  $stno = $stuList['stno'];
                  $stuname = $stuList['name'];
                  $stuphone = $stuList['phonenum'];
                  $sex = $stuList['sex'];
                  $score = $stuList['grade'];
                  if ($score == '')
                  {
                    $score = "暂无成绩";
                  }
                  $isgood = "非优秀";
                  $isgraduate = "未结业";
                  if ($stuList['isgood'] == 1)
                  {
                    $isgood = "优&nbsp;&nbsp;&nbsp;秀";
                  }
                  if ($stuList['isgraduate'] == 1) {
                    $isgraduate = "已结业";
                  }

                  echo "<tr>";
                  echo '<td><input type="checkbox" name="xueyuan" class="form-control check-change" value="'.$stno.'"></td>';
                  echo "<td>{$stno}</td>";
                  echo "<td>{$stuname}</td>";
                  echo "<td>{$stuphone}</td>";
                  echo "<td>{$sex}</td>";
                  echo '<td><button class="btn btn-default youxiu" title="点击可修改状态">'.$isgood.'</button></td>';
                  echo '<td><button class="btn btn-default biye" title="点击可修改状态">'.$isgraduate.'</button></td>';
                  echo "<td>{$score}</td>";
                  echo '<td><img class="del-icon" src="/images/2.jpg"></td>';
                  echo "</tr>";
                }
            ?>
            </table>
            <div class="footer-fenye">
              <ul class="pager">
              <?php
                global $arrList;
                $paginator_all=$this->paginator_all;
                echo $this->paginationControl($this->paginator_studentinfo,
                'Elastic',//页码样式 
                'admin/pagination_control.phtml'//页码模板
                );
              ?>
              </ul>
            </div>
            <button type="button" id="del-all" class="btn btn-danger">一键删除</button>
        </div>
        <div class="banzhuren">
          <span>班主任：</span>
          <span id="name-bzr">班主任姓名</span>
        </div>
        <!-- 优秀学员 -->
        <div class="students-yx info">
          <label for="st-yx">优秀学员姓名（人数占所带学生总人数10%）</label>
          <textarea name="st-yx" id="st-yx" class="form-control" disabled>自动显示优秀学员姓名</textarea>
        </div>
        <!-- 学员素质 -->
        <div class="info">
          <label for="xy-sz">如何严格招生，保证学员素质（措施、效果）</label>
          <textarea name="xy-sz" id="xy-sz" class="form-control" disabled><?php echo $this->xysz;?>
          </textarea>
        </div>
        <!-- 学习情况 -->
        <div class="info">
          <label for="study-content">组织集中学习情况（主题、次数、效果）</label>
          <textarea name="study-content" id="study-content" class="form-control" disabled><?php echo $this->study;?>
          </textarea>
        </div>
        <!-- 讨论情况 -->
        <div class="info">
          <label for="taolun-content">组织讨论情况（主题、次数、效果）</label>
          <textarea name="taolun-content" id="taolun-content" class="form-control" disabled><?php echo $this->taolun;?>
          </textarea>
        </div>
        <!-- 实践活动情况 -->
        <div class="info">
          <label for="">开展实践活动情况（主题、形式、意义、效果）</label>
          <textarea name="shijian-content" id="shijian-content" class="form-control" disabled><?php echo $this->shijian;?>
          </textarea>
        </div>
        <div class="info">
          <button type="button" class="btn btn-info" id="prod-excel">生成excel</button>
        </div>
        
      </div>
    </div>
    <?php
     }
     else
     {
    ?>
      <div class="main-content">
        <div class="tishi">
          可按上面条件查询各班级情况
        </div>
      </div>
    <?php
     }
    ?>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/artDialog.js"></script>
    <script type="text/javascript" src="/js/xyinfo.js"></script>
  </body>
</html>